version: '3'

services: 
  db: 
    image: postgres
    volumes: 
      - db_data:/var/lib/postgresql
    restart: always

  api: 
    depends_on: 
      - db
    image: naotoyamaguchi/surfgarage-api
    ports: 
      - "3001:3000"
    restart: always
    environment: 
      POSTGRES_HOST: db
      POSTGRES_USER: postgres

volumes: 
  db_data: 